//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_DataView
    {
        public int LINE { get; set; }
        public System.DateTime GET_TIME { get; set; }
        public int LINE_STATUS { get; set; }
        public int SPEED { get; set; }
        public decimal SIZE { get; set; }
        public decimal THICK { get; set; }
        public int PLAN { get; set; }
        public int RESULT { get; set; }
        public bool UNCOIL_expand { get; set; }
        public int UNCOIL_Speed { get; set; }
        public bool RECOIL_expand { get; set; }
        public int RECOIL_Speed { get; set; }
        public bool SCRAP_WINDER_L_expand { get; set; }
        public int SCRAP_WINDER_L_Speed { get; set; }
        public int SCRAP_WINDER_R_Speed { get; set; }
        public bool SCRAP_WINDER_R_expand { get; set; }
        public int Outside_Diameter_UC { get; set; }
        public int Outside_Diameter_RC { get; set; }
        public int Inside_Diameter_UC { get; set; }
        public int Inside_Diameter_RC { get; set; }
        public int Cutting_Mode { get; set; }
        public bool Preparetion { get; set; }
        public int COIL_DIVIDE_SET { get; set; }
        public int Weight { get; set; }
        public bool Side_Guid_Status { get; set; }
        public bool Slitter_Status { get; set; }
        public Nullable<decimal> Motor_Uncoiler_A { get; set; }
        public Nullable<decimal> Motor_Tree_Roll_A { get; set; }
        public Nullable<decimal> Motor_Slitter_A { get; set; }
        public Nullable<decimal> Motor_Roll_Tension_A { get; set; }
        public Nullable<decimal> Motor_Recoiler_A { get; set; }
        public Nullable<decimal> GearBox_Uncoiler_A { get; set; }
        public Nullable<decimal> GearBox_Tree_Roll_A { get; set; }
        public Nullable<decimal> GearBox_Slitter_A { get; set; }
        public Nullable<decimal> GearBox_Roll_Tension_A { get; set; }
        public Nullable<decimal> GearBox_Recoiler_A { get; set; }
        public Nullable<decimal> Motor_Uncoiler_V { get; set; }
        public Nullable<decimal> Motor_Tree_Roll_V { get; set; }
        public Nullable<decimal> Motor_Slitter_V { get; set; }
        public Nullable<decimal> Motor_Roll_Tension_V { get; set; }
        public Nullable<decimal> Motor_Recoiler_V { get; set; }
        public Nullable<decimal> GearBox_Uncoiler_V { get; set; }
        public Nullable<decimal> GearBox_Tree_Roll_V { get; set; }
        public Nullable<decimal> GearBox_Slitter_V { get; set; }
        public Nullable<decimal> GearBox_Roll_Tension_V { get; set; }
        public Nullable<decimal> GearBox_Recoiler_V { get; set; }
        public Nullable<decimal> Motor_Uncoiler_Temp { get; set; }
        public Nullable<decimal> Motor_Tree_Roll_Temp { get; set; }
        public Nullable<decimal> Motor_Slitter_Temp { get; set; }
        public Nullable<decimal> Motor_Roll_Tension_Temp { get; set; }
        public Nullable<decimal> Motor_Recoiler_Temp { get; set; }
        public Nullable<decimal> GearBox_Uncoiler_Temp { get; set; }
        public Nullable<decimal> GearBox_Tree_Roll_Temp { get; set; }
        public Nullable<decimal> GearBox_Slitter_Temp { get; set; }
        public Nullable<decimal> GearBox_Roll_Tension_Temp { get; set; }
        public Nullable<decimal> GearBox_Recoiler_Temp { get; set; }
        public Nullable<bool> Laser_Scanner_1 { get; set; }
        public Nullable<bool> Laser_Scanner_2 { get; set; }
        public Nullable<bool> Laser_Scanner_3 { get; set; }
        public Nullable<bool> Laser_Scanner_4 { get; set; }
        public Nullable<bool> Laser_Scanner_5 { get; set; }
        public Nullable<bool> Laser_Scanner_6 { get; set; }
        public Nullable<bool> Laser_Scanner_7 { get; set; }
        public Nullable<bool> Laser_Scanner_8 { get; set; }
        public Nullable<bool> Laser_Scanner_9 { get; set; }
        public Nullable<bool> Laser_Scanner_10 { get; set; }
        public Nullable<bool> Laser_Scanner_11 { get; set; }
        public Nullable<bool> Laser_Scanner_12 { get; set; }
        public Nullable<bool> Laser_Scanner_13 { get; set; }
        public Nullable<bool> Laser_Scanner_14 { get; set; }
        public Nullable<bool> Laser_Scanner_15 { get; set; }
        public Nullable<bool> Laser_Scanner_16 { get; set; }
        public Nullable<bool> Laser_Scanner_17 { get; set; }
        public Nullable<bool> Laser_Scanner_18 { get; set; }
        public Nullable<bool> Laser_Scanner_19 { get; set; }
        public Nullable<bool> Laser_Scanner_20 { get; set; }
        public Nullable<bool> Door_Sensor_1 { get; set; }
        public Nullable<bool> Door_Sensor_2 { get; set; }
        public Nullable<bool> Door_Sensor_3 { get; set; }
        public Nullable<bool> Door_Sensor_4 { get; set; }
        public Nullable<bool> Door_Sensor_5 { get; set; }
        public Nullable<bool> Gate_1 { get; set; }
        public Nullable<bool> Gate_2 { get; set; }
        public Nullable<bool> Gate_3 { get; set; }
        public Nullable<bool> Signal_Tower_1 { get; set; }
        public Nullable<bool> Signal_Tower_2 { get; set; }
        public Nullable<bool> Signal_Tower_3 { get; set; }
        public Nullable<bool> Signal_Tower_4 { get; set; }
        public Nullable<bool> Signal_Tower_5 { get; set; }
        public Nullable<bool> Signal_Tower_6 { get; set; }
        public Nullable<bool> Safety_pin_1 { get; set; }
        public Nullable<bool> Safety_pin_2 { get; set; }
        public Nullable<bool> Safety_pin_3 { get; set; }
        public Nullable<bool> Safety_pin_4 { get; set; }
        public Nullable<bool> Safety_pin_5 { get; set; }
        public Nullable<bool> Safety_pin_6 { get; set; }
        public Nullable<bool> Safety_pin_7 { get; set; }
        public Nullable<bool> Safety_pin_8 { get; set; }
        public Nullable<bool> Safety_pin_9 { get; set; }
        public Nullable<bool> Safety_pin_10 { get; set; }
        public Nullable<bool> Safety_pin_11 { get; set; }
        public Nullable<bool> Safety_pin_12 { get; set; }
        public Nullable<bool> Safety_pin_13 { get; set; }
        public Nullable<bool> Safety_pin_14 { get; set; }
        public Nullable<System.DateTime> Error_Time { get; set; }
        public Nullable<int> Error_Number { get; set; }
    }
}
