//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Mapping
    {
        public int LINE_TYPE { get; set; }
        public int Error_No { get; set; }
        public string Language { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
    }
}
