//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Error
    {
        public int LINE { get; set; }
        public System.DateTime Error_Time { get; set; }
        public int Error_Number { get; set; }
    }
}
