//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Work
    {
        public int LINE { get; set; }
        public System.DateTime GET_TIME { get; set; }
        public int LINE_STATUS { get; set; }
        public int SPEED { get; set; }
        public decimal SIZE { get; set; }
        public decimal THICK { get; set; }
        public int PLAN { get; set; }
        public int RESULT { get; set; }
        public bool UNCOIL_expand { get; set; }
        public int UNCOIL_Speed { get; set; }
        public bool RECOIL_expand { get; set; }
        public int RECOIL_Speed { get; set; }
        public bool SCRAP_WINDER_L_expand { get; set; }
        public int SCRAP_WINDER_L_Speed { get; set; }
        public bool SCRAP_WINDER_R_expand { get; set; }
        public int SCRAP_WINDER_R_Speed { get; set; }
        public int Outside_Diameter_UC { get; set; }
        public int Outside_Diameter_RC { get; set; }
        public int Inside_Diameter_UC { get; set; }
        public int Inside_Diameter_RC { get; set; }
        public int Cutting_Mode { get; set; }
        public bool Preparetion { get; set; }
        public int COIL_DIVIDE_SET { get; set; }
        public int Weight { get; set; }
        public bool Side_Guid_Status { get; set; }
        public bool Slitter_Status { get; set; }
        public Nullable<bool> PILER_NO1 { get; set; }
        public Nullable<bool> PILER_NO2 { get; set; }
    }
}
