//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_A
    {
        public int LINE { get; set; }
        public System.DateTime GET_TIME { get; set; }
        public decimal Motor_Uncoiler { get; set; }
        public decimal Motor_Tree_Roll { get; set; }
        public decimal Motor_Slitter { get; set; }
        public decimal Motor_Roll_Tension { get; set; }
        public decimal Motor_Recoiler { get; set; }
        public decimal GearBox_Uncoiler { get; set; }
        public decimal GearBox_Tree_Roll { get; set; }
        public decimal GearBox_Slitter { get; set; }
        public decimal GearBox_Roll_Tension { get; set; }
        public decimal GearBox_Recoiler { get; set; }
    }
}
