//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_security_Sensor
    {
        public int LINE { get; set; }
        public System.DateTime GET_TIME { get; set; }
        public bool Laser_Scanner_1 { get; set; }
        public bool Laser_Scanner_2 { get; set; }
        public bool Laser_Scanner_3 { get; set; }
        public bool Laser_Scanner_4 { get; set; }
        public bool Laser_Scanner_5 { get; set; }
        public bool Laser_Scanner_6 { get; set; }
        public bool Laser_Scanner_7 { get; set; }
        public bool Laser_Scanner_8 { get; set; }
        public bool Laser_Scanner_9 { get; set; }
        public bool Laser_Scanner_10 { get; set; }
        public bool Laser_Scanner_11 { get; set; }
        public bool Laser_Scanner_12 { get; set; }
        public bool Laser_Scanner_13 { get; set; }
        public bool Laser_Scanner_14 { get; set; }
        public bool Laser_Scanner_15 { get; set; }
        public bool Laser_Scanner_16 { get; set; }
        public bool Laser_Scanner_17 { get; set; }
        public bool Laser_Scanner_18 { get; set; }
        public bool Laser_Scanner_19 { get; set; }
        public bool Laser_Scanner_20 { get; set; }
        public bool Door_Sensor_1 { get; set; }
        public bool Door_Sensor_2 { get; set; }
        public bool Door_Sensor_3 { get; set; }
        public bool Door_Sensor_4 { get; set; }
        public bool Door_Sensor_5 { get; set; }
        public bool Gate_1 { get; set; }
        public bool Gate_2 { get; set; }
        public bool Gate_3 { get; set; }
        public bool Signal_Tower_1 { get; set; }
        public bool Signal_Tower_2 { get; set; }
        public bool Signal_Tower_3 { get; set; }
        public bool Signal_Tower_4 { get; set; }
        public bool Signal_Tower_5 { get; set; }
        public bool Signal_Tower_6 { get; set; }
        public bool Safety_pin_1 { get; set; }
        public bool Safety_pin_2 { get; set; }
        public bool Safety_pin_3 { get; set; }
        public bool Safety_pin_4 { get; set; }
        public bool Safety_pin_5 { get; set; }
        public bool Safety_pin_6 { get; set; }
        public bool Safety_pin_7 { get; set; }
        public bool Safety_pin_8 { get; set; }
        public bool Safety_pin_9 { get; set; }
        public bool Safety_pin_10 { get; set; }
        public bool Safety_pin_11 { get; set; }
        public bool Safety_pin_12 { get; set; }
        public bool Safety_pin_13 { get; set; }
        public bool Safety_pin_14 { get; set; }
    }
}
