//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Report.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mac_Spec
    {
        public System.Guid ID { get; set; }
        public decimal Think_W { get; set; }
        public decimal Think_A { get; set; }
        public decimal Think_M { get; set; }
        public decimal Order_Size_W { get; set; }
        public decimal Order_Size_A { get; set; }
        public decimal Order_Size_M { get; set; }
        public decimal Uncoil_W { get; set; }
        public decimal Uncoil_A { get; set; }
        public decimal Uncoil_M { get; set; }
        public decimal Recoil_W { get; set; }
        public decimal Recoil_A { get; set; }
        public decimal Recoil_M { get; set; }
        public decimal Speed_W { get; set; }
        public decimal Speed_A { get; set; }
        public decimal Speed_M { get; set; }
        public decimal Work_rate_W { get; set; }
        public decimal Work_rate_A { get; set; }
        public decimal Work_rate_M { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Modifly_Date { get; set; }
        public int Line_No { get; set; }
        public int LINE_TYPE { get; set; }
        public string Line_Name { get; set; }
    }
}
