//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Server_Check.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory_Report_Iog
    {
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> Reporter1 { get; set; }
        public System.Guid WorkerID1 { get; set; }
        public Nullable<System.Guid> WorkerID2 { get; set; }
        public Nullable<System.Guid> WorkerID3 { get; set; }
        public Nullable<System.Guid> WorkerID4 { get; set; }
        public System.Guid FileID { get; set; }
    }
}
