//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Server_Check.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SND_SystemEntities : DbContext
    {
        public SND_SystemEntities()
               : base(ConnectionString)
        {
        }
        public static string ConnectionString { get; set; } = "name=SND_SystemEntities";
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Factory_Report_Iog> Factory_Report_Iog { get; set; }
        public virtual DbSet<SNOS_IP_Checklist> SNOS_IP_Checklist { get; set; }
    }
}
