//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOS_Server_Check.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNOS_IP_Checklist
    {
        public string STM_ID { get; set; }
        public string Cus_Name { get; set; }
        public string IP_Address_CS { get; set; }
        public string IP_Address_SND { get; set; }
        public bool Contact_status { get; set; }
    }
}
