//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCONF
    {
        public short FUNCNO { get; set; }
        public short FUNCSUBNO { get; set; }
        public Nullable<int> INT_VAL { get; set; }
        public Nullable<decimal> DEC_VAL { get; set; }
        public string VCHAR_VAL { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
