//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLINE_TYPE
    {
        public short LINE_TYPE { get; set; }
        public string ENNAME { get; set; }
        public string JPNAME { get; set; }
        public short SHEET_COUNT { get; set; }
    }
}
