//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSEQERRCD
    {
        public short LINE_TYPE { get; set; }
        public int ERRNO { get; set; }
        public string LANG { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
