//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class UTLRATE_Entities : DbContext
    {
        public UTLRATE_Entities() : base(ConnectionString)
        {

        }
        public static string ConnectionString { get; set; } = "name=UTLRATE_Entities";

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<DCONF> DCONFs { get; set; }
        public virtual DbSet<DDRIVE> DDRIVEs { get; set; }
        public virtual DbSet<DPROC> DPROCs { get; set; }
        public virtual DbSet<DPROCING> DPROCINGs { get; set; }
        public virtual DbSet<DTROUBLELOG> DTROUBLELOGs { get; set; }
        public virtual DbSet<MBOARD_INFO> MBOARD_INFO { get; set; }
        public virtual DbSet<MEVENT> MEVENTs { get; set; }
        public virtual DbSet<MLINE_INFO> MLINE_INFO { get; set; }
        public virtual DbSet<MLINE_TYPE> MLINE_TYPE { get; set; }
        public virtual DbSet<MSEQERRCD> MSEQERRCDs { get; set; }
        public virtual DbSet<V_Top_Now_DPROC> V_Top_Now_DPROC { get; set; }
        public virtual DbSet<VDRIVE> VDRIVEs { get; set; }
        public virtual DbSet<VLINE> VLINEs { get; set; }
        public virtual DbSet<VPROC> VPROCs { get; set; }
        public virtual DbSet<VPROCING> VPROCINGs { get; set; }
    }
}
