//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Top_Now_DPROC
    {
        public int LINE { get; set; }
        public decimal SIZE { get; set; }
        public decimal THICK { get; set; }
        public short SHEET_SCHED { get; set; }
        public short SHEET_RESULT { get; set; }
        public System.DateTime START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public short SPEED { get; set; }
    }
}
