//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Rate_SNOS.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLINE
    {
        public int LINE { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_TYPE { get; set; }
        public Nullable<int> PORT_TCP { get; set; }
        public Nullable<int> PORT_UDP { get; set; }
        public short ENABLE { get; set; }
        public string IP { get; set; }
    }
}
